#!/usr/bin/env node

/* eslint no-console: 0 */

const spawn = require('child_process').spawn
const readline = require('readline')

const rpc = {
  pause: 'game-pause',
  resume: 'game-resume',
  start: 'game-start',
  stats: 'game-stats',
  stop: 'game-stop',
  help: 'game-help'
}

const motd = [
  'This is kind of game server management console. \n',
  'Type "help" to list all available commands \n'
]

const cmd = process.argv[2]

function isAllowed(cmd) {
  return Object.keys(rpc).indexOf(cmd) > -1
}

function cli() {
  const iface = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  })

  motd.forEach((m) => iface.write(m))

  iface.setPrompt('game> ')

  iface.on('line', (line) => {
    if (line.trim() === '') {
      return iface.prompt()
    }

    let cmd = line.toString()

    if (isAllowed(cmd)) {
      let command

      iface.pause()

      command = spawn(rpc[cmd])
      command.stdout.pipe(process.stdout)
      command.stderr.pipe(process.stderr)

      command.on('exit', () => {
        iface.prompt()
      })
    } else {
      console.log('Command not recognized')
      console.log('Type "help" to list all available commands')
      iface.prompt()
    }
  })

  iface.prompt()
}

if (isAllowed(cmd)) {
  let command = spawn(rpc[cmd])
  command.stdout.pipe(process.stdout)
  command.stderr.pipe(process.stderr)
} else {
  cli()
}
